"""Common types and utilities."""

from .common_types import (
    CAP_CHESS,
    DEFAULT_HTTP_TIMEOUT,
    ChatMessage,
    CompletionResult,
    ModelInfo,
    ModelProvider,
    is_chess_capable,
    is_free_tier,
)
from .exceptions import (
    AuthenticationError,
    AuthError,
    BenchmarkError,
    ChessFightError,
    ConnectionError,
    GameExecutionError,
    InvalidApiKeyError,
    ModelNotFoundError,
    MoveValidationError,
    NetworkError,
    NoProvidersConfiguredError,
    ProviderAPIError,
    ProviderError,
    ProviderUnavailableError,
    QuotaExceededError,
    RateLimitError,
    SetupError,
    TimeoutError,
    is_retryable,
)
from .retry import (
    RETRY_MOVE_PARSE,
    RETRY_RATE_LIMIT,
    RETRY_TRANSIENT,
    RetryPolicy,
    is_retryable_error,
    retry_async,
)

__all__ = [
    "CAP_CHESS",
    "DEFAULT_HTTP_TIMEOUT",
    "RETRY_MOVE_PARSE",
    "RETRY_RATE_LIMIT",
    "RETRY_TRANSIENT",
    "AuthError",
    "AuthenticationError",
    "BenchmarkError",
    "ChatMessage",
    "ChessFightError",
    "CompletionResult",
    "ConnectionError",
    "GameExecutionError",
    "InvalidApiKeyError",
    "ModelInfo",
    "ModelNotFoundError",
    "ModelProvider",
    "MoveValidationError",
    "NetworkError",
    "NoProvidersConfiguredError",
    "ProviderAPIError",
    "ProviderError",
    "ProviderUnavailableError",
    "QuotaExceededError",
    "RateLimitError",
    "RetryPolicy",
    "SetupError",
    "TimeoutError",
    "is_chess_capable",
    "is_free_tier",
    "is_retryable",
    "is_retryable_error",
    "retry_async",
]
